### ISSUE TITLE
Looks like init might contain deprecated methods

### ISSUE THREAD

**Issue by jakeisonline** [guard/guard-compass#13]
After running `guard init compass` then, then running `guard`, the following is output

```
********************
DEPRECATION WARNING!
********************
            You have a string in your Guardfile watch patterns that seem to represent a Regexp.
            Guard matches String with == and Regexp with Regexp#match.
            You should either use plain String (without Regexp special characters) or real Regexp.

"^src/(.*)\.s[ac]ss" has been converted to /^src\/(.*)\.s[ac]ss/
```

**Comment by LimeBlast** [comment]
I'm getting the same error, but I'm not sure what I'm meant to use in my Guardfile to prevent this message.

**Comment by rymai** [comment]
Hi guys,

The message should be self-explanatory:

> You should either use plain String (without Regexp special characters) or real Regexp.

In your case, simply replace `"^src/(.*)\.s[ac]ss"` with `/^src\/(.*)\.s[ac]ss/` in your Guardfile.

Btw, @oliamb you should probably sync guard/guard-compass and oliamb/guard-compass (and possibly disable issues for one of them)!

**Comment by LimeBlast** [comment]
@rymai sorry, I had a bit of a brainfart, managed to sort it now, cheers.

**Comment by rymai** [comment]
No problem!
