### ISSUE TITLE
A version that includes notifications

### ISSUE THREAD

**Issue by ghost** [guard/guard-compass#17]
I'm really interested in the notifications development mentioned in the roadmap for v0.1.0 but installing from http://rubygems.org is only giving me v0.6.0.

Is v0.1.0 available for use yet or is it still just a point on the roadmap? If it is available now, how might I go about getting hold of it? Specifying this Git repo in my Gemfile seems to just leave me with v0.6.0 still.

Please forgive my ignorance, I'm pretty new to using Ruby Gems.

**Comment by rymai** [comment]
Hi, unfortunately it's only in the roadmap and there seem to be no maintenance/development of the gem. I'll contact the author to see if I can have the rights to release new versions of the gem. Btw, FYI you can see all the gem's versions here: http://rubygems.org/gems/guard-compass

**Comment by ghost** [comment]
Thanks for the quick reply.

I'll keep an eye on things to see if any new versions pop up in future then. Good luck obtaining rights.

Thanks for the link too - I think I already found that one but wasn't sure I was getting the whole picture, what with being a total Ruby nooby :D
