### ISSUE TITLE
Load order not preserved

### ISSUE THREAD

**Issue by jtwalters** [guard/guard-compass#19]
Load order does not seem to be preserved and will have incorrect results if you use multiple stylesheets in development (i.e. modular css).

The only workaround I can think of might be renaming all of the stylesheets to be in the correct alpha-order. e.g. 00_first.scss, 10_second.scss, 20_third.scss, etc.

**Comment by jtwalters** [comment]
This may have something to do with link tags vs. style @import

**Comment by rymai** [comment]
Hi, do you think it's a guard-compass specific issue? If yes, please feel free to submit a pull-request. Thanks!

**Comment by jtwalters** [comment]
Closing since I was able to get this project to work with standard link tags.
