### ISSUE TITLE
slow updates

### ISSUE THREAD

**Issue by KenMor** [guard/guard-compass#5]
I'm using guard and guard-compass in windows 7 with livereload on Chrome (which also has huge delays) and have had waits of ten to twenty seconds (or more) for the system to understand that a save has been made. I re re installed yajly-ruby to speed things up, and for the first time used bundler to do so, and at that point  guard lost compass. I've gone back to using compass by itself and reloading my site by hand. Any suggestions on the problem?
Guardfile
guard 'compass' do
  watch(%r{(css/.+.scss)})
end

guard 'livereload' do
  watch(%r{(html|php)})  
  watch(%r{(css/.+.css)}) 
  watch(%r{(js/.+.js)}) 
 end
Gemfile
source "http://rubygems.org"
gem 'guard-compass'
# gem "rails"

some speed loss has been due to following too many imprecise instructions. I had the guard gem populated with both linux & osx tools. Dumping those sped it up, but it still took saving html twice to trigger it to reload.

group :development do
  gem 'guard'
  gem 'rb-fchange', :require => false
  gem 'rb-notifu'
  gem 'win32console'
  gem 'guard-compass'
  gem 'guard-livereload'
end

The situation now is that the first save of html changes does nothing. The second save does nothing. The third save finally updates the html. It doesn't update scss to css at all.

**Comment by rymai** [comment]
Hi,

If you still have this issue, please be sure to update Guard and guard-compass and re-open this issue, thanks!
